version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-deadline
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password